(function(){
  'use strict';
  const KEY='esun_power_consumption_schedule_v1';
  let schedule={};
  const $=s=>document.querySelector(s);
  const $$=s=>Array.from(document.querySelectorAll(s));
  const n=(v,d=0)=>Number.isFinite(Number(v))?Number(v):d;
  const pad=v=>String(v).padStart(2,'0');
  const fmt=v=>n(v).toLocaleString('es-CO',{minimumFractionDigits:2,maximumFractionDigits:2});
  function load(){try{const x=JSON.parse(localStorage.getItem(KEY)||'{}');if(x&&typeof x==='object')schedule=x;}catch(e){schedule={};}}
  function save(){try{localStorage.setItem(KEY,JSON.stringify(schedule));}catch(e){}}
  function toMin(v){if(!/^\d{2}:\d{2}$/.test(v||''))return null;const [h,m]=v.split(':').map(Number);return h*60+m;}
  function fromMin(v){v=((v%1440)+1440)%1440;return pad(Math.floor(v/60))+':'+pad(v%60);}
  function duration(a,b){const s=toMin(a),e=toMin(b);if(s===null||e===null)return 0;let d=e-s;if(d<0)d+=1440;return d/60;}
  function normalize(id,row){const old=schedule[id]||{};let start=old.start||'08:00';let end=old.end||'';const hours=n(row?.querySelector('[data-field="hours"]')?.value,0);if(!end)end=fromMin((toMin(start)??480)+hours*60);schedule[id]={start,end};return schedule[id];}
  function css(){if($('#cmScheduleStyles'))return;const s=document.createElement('style');s.id='cmScheduleStyles';s.textContent=`
.cm-time{width:100%;min-width:86px!important;padding:8px 6px!important;font-size:12px!important}.cm-hours-auto{background:#2f2d26!important;border-color:#8a7220!important;font-weight:700!important;text-align:center}.cm-schedule-note{margin-top:12px;padding:10px;background:#302d24;border:1px solid #655b3e;border-radius:7px;font-size:12px;color:#ddd}.cm-hourly-card{margin-top:14px;background:#252525;border:1px solid #414141;border-radius:8px;padding:14px}.cm-hourly-card h3{margin:0 0 5px;font-size:16px}.cm-hourly-card p{margin:0 0 10px;color:#bbb;font-size:12px}.cm-hourly-svg{width:100%;height:270px;display:block}.cm-hourly-label{fill:#ccc;font-size:9px}.cm-hourly-grid{stroke:#444;stroke-width:1}.cm-hourly-axis{stroke:#777;stroke-width:1}.cm-hourly-bar{fill:#f2b705}.cm-hourly-backup{fill:#6e8799}@media(max-width:900px){.cm-hourly-svg{min-width:720px}.cm-hourly-wrap{overflow-x:auto}}`;document.head.appendChild(s);}
  function ensureHeaders(){const table=$('.cm-table');if(!table)return;const head=table.querySelector('thead tr');if(head&&!head.querySelector('[data-schedule-head="start"]')){const th=head.querySelectorAll('th')[4];if(th){const a=document.createElement('th');a.dataset.scheduleHead='start';a.textContent='Hora inicio';th.parentNode.insertBefore(a,th);const b=document.createElement('th');b.dataset.scheduleHead='end';b.textContent='Hora apagado';th.parentNode.insertBefore(b,th);}}}
  function rowData(tr){const vals={};tr.querySelectorAll('[data-field]').forEach(x=>vals[x.dataset.field]=x.value);return{qty:n(vals.qty,1),power:n(vals.power,0),util:Math.max(0,Math.min(100,n(vals.util,100))),equipment:vals.equipment||'Carga'};}
  function setHours(tr,hrs){const h=tr.querySelector('[data-field="hours"]');if(!h)return;h.value=hrs.toFixed(2).replace(/\.00$/,'');h.readOnly=true;h.classList.add('cm-hours-auto');h.title='Calculado automáticamente a partir de Hora inicio y Hora apagado';h.dispatchEvent(new Event('input',{bubbles:true}));}
  function decorate(){const body=$('#consumptionMatrixBody');if(!body)return;css();ensureHeaders();body.querySelectorAll('tr[data-id]').forEach(tr=>{const id=tr.dataset.id,cfg=normalize(id,tr),hourCell=tr.querySelector('[data-field="hours"]')?.closest('td');if(!hourCell)return;if(!tr.querySelector('[data-schedule="start"]')){const td=document.createElement('td');td.innerHTML=`<input type="time" class="cm-time" data-schedule="start" value="${cfg.start}">`;hourCell.parentNode.insertBefore(td,hourCell);}if(!tr.querySelector('[data-schedule="end"]')){const td=document.createElement('td');td.innerHTML=`<input type="time" class="cm-time" data-schedule="end" value="${cfg.end}">`;hourCell.parentNode.insertBefore(td,hourCell);}setHours(tr,duration(cfg.start,cfg.end));});renderChart();}
  function profile(){const total=new Array(24).fill(0),backup=new Array(24).fill(0);$$('#consumptionMatrixBody tr[data-id]').forEach(tr=>{const id=tr.dataset.id,cfg=schedule[id];if(!cfg)return;const d=rowData(tr),s=toMin(cfg.start),e=toMin(cfg.end);if(s===null||e===null)return;let dur=e-s;if(dur<0)dur+=1440;if(dur===0)return;const kw=d.qty*d.power*d.util/100/1000;for(let h=0;h<24;h++){let active=0;for(let m=0;m<60;m+=15){const t=h*60+m,rel=(t-s+1440)%1440;if(rel<dur)active+=.25;}const val=kw*active;total[h]+=val;if(tr.querySelector('[data-backup]')?.classList.contains('active'))backup[h]+=val;}});return{total,backup};}
  function renderChart(){const panel=$('#panel-matrix');if(!panel)return;let card=$('#cmHourlyCard');if(!card){card=document.createElement('div');card.id='cmHourlyCard';card.className='cm-hourly-card';const note=panel.querySelector('.cm-note');if(note)note.after(card);else panel.appendChild(card);}const {total,backup}=profile(),max=Math.max(1,...total),W=1080,H=270,L=44,R=12,T=18,B=42,plotW=W-L-R,plotH=H-T-B,bw=plotW/24*.62,gap=plotW/24;let svg=`<div><h3>Perfil de consumo por hora</h3><p>La energía horaria se obtiene directamente del intervalo Hora inicio → Hora apagado de cada equipo. Las horas/día de la matriz son calculadas automáticamente.</p></div><div class="cm-hourly-wrap"><svg class="cm-hourly-svg" viewBox="0 0 ${W} ${H}" role="img" aria-label="Gráfico de consumo eléctrico por hora">`;for(let g=0;g<=4;g++){const y=T+plotH-g*plotH/4,v=max*g/4;svg+=`<line class="cm-hourly-grid" x1="${L}" x2="${W-R}" y1="${y}" y2="${y}"/><text class="cm-hourly-label" x="${L-6}" y="${y+3}" text-anchor="end">${fmt(v)}</text>`;}svg+=`<line class="cm-hourly-axis" x1="${L}" x2="${W-R}" y1="${T+plotH}" y2="${T+plotH}"/>`;total.forEach((v,i)=>{const x=L+i*gap+(gap-bw)/2,bh=v/max*plotH,y=T+plotH-bh,bhh=backup[i]>0?backup[i]/max*plotH:0;svg+=`<rect class="cm-hourly-bar" x="${x}" y="${y}" width="${bw}" height="${Math.max(0,bh)}" rx="2"><title>${pad(i)}:00 — ${fmt(v)} kWh en carga activa</title></rect>`;if(bhh>0)svg+=`<rect class="cm-hourly-backup" x="${x+2}" y="${y}" width="${Math.max(2,bw-4)}" height="${Math.min(bhh,bh)}" rx="1"><title>${pad(i)}:00 — ${fmt(backup[i])} kWh respaldados</title></rect>`;svg+=`<text class="cm-hourly-label" x="${x+bw/2}" y="${H-20}" text-anchor="middle">${pad(i)}</text>`;});svg+=`<text class="cm-hourly-label" x="${W/2}" y="${H-3}" text-anchor="middle">Hora del día</text><text class="cm-hourly-label" x="10" y="${T+plotH/2}" transform="rotate(-90 10 ${T+plotH/2})" text-anchor="middle">kWh por hora</text></svg></div>`;card.innerHTML=svg;}
  function patchProjectState(){if(typeof window.getProjectFormState==='function'&&!window.getProjectFormState.__schedulePatched){const original=window.getProjectFormState,fn=function(){const state=original();state.fields=state.fields||{};state.fields.consumptionSchedule={...schedule};return state;};fn.__schedulePatched=true;window.getProjectFormState=fn;}if(typeof window.setProjectFormState==='function'&&!window.setProjectFormState.__schedulePatched){const original=window.setProjectFormState,fn=function(state){const x=state?.fields?.consumptionSchedule;if(x&&typeof x==='object')schedule={...schedule,...x};original(state);setTimeout(decorate,60);};fn.__schedulePatched=true;window.setProjectFormState=fn;}}
  function bind(){const body=$('#consumptionMatrixBody');if(!body||body.dataset.scheduleBound)return;if(!body)return;body.dataset.scheduleBound='1';body.addEventListener('input',e=>{const input=e.target;if(!input.matches('[data-schedule]'))return;const tr=input.closest('tr'),id=tr?.dataset.id;if(!id)return;const cfg=normalize(id,tr);cfg[input.dataset.schedule]=input.value;schedule[id]=cfg;setHours(tr,duration(cfg.start,cfg.end));save();renderChart();});body.addEventListener('change',e=>{if(e.target.matches('[data-schedule]')){const tr=e.target.closest('tr');if(tr){const id=tr.dataset.id,cfg=normalize(id,tr);cfg[e.target.dataset.schedule]=e.target.value;schedule[id]=cfg;setHours(tr,duration(cfg.start,cfg.end));save();renderChart();}}});}
  function init(){load();patchProjectState();const observer=new MutationObserver(()=>{patchProjectState();bind();decorate();});observer.observe(document.body,{childList:true,subtree:true});setTimeout(()=>{patchProjectState();bind();decorate();},100);setInterval(()=>{patchProjectState();bind();decorate();},1200);}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
