(function(){
'use strict';
const $=id=>document.getElementById(id);
const fmt=(v,d=2)=>Number(v||0).toLocaleString('es-CO',{minimumFractionDigits:d,maximumFractionDigits:d});
const num=v=>Number(v||0);
function matrixBackup(){return{daily:num(window.__esunConsumptionMatrixBackupDaily),monthly:num(window.__esunConsumptionMatrixBackupMonthly),annual:num(window.__esunConsumptionMatrixBackupAnnual)}}
function selectedEquipment(){const mode=$('equipmentMode')?.value||'inverter';if(mode==='solar_vfd'){const s=$('solarVfd'),o=s?.selectedOptions?.[0],tech=$('solarVfdTechCard');const detail=(tech?.innerText||o?.textContent||'').replace(/\$\s?[\d.,]+/g,'').replace(/\s+/g,' ').trim();return{type:'vfd',detail:detail||'Variador de frecuencia solar seleccionado'}}const s=$('inverter'),o=s?.selectedOptions?.[0],tech=$('inverterTechCard');const detail=(tech?.innerText||o?.textContent||'').replace(/\$\s?[\d.,]+/g,'').replace(/\s+/g,' ').trim();return{type:'inverter',detail:detail||'Inversor fotovoltaico seleccionado'}}
function vfdPower(){const s=$('solarVfd'),txt=s?.selectedOptions?.[0]?.textContent||'';const m=txt.match(/([\d.,]+)\s*kW/i);return m?m[1]+' kW':'—'}
function ensureFields(){const grid=document.querySelector('.qtech-grid');if(!grid)return;const old=$('qqEquipmentDetailRow');if(old)old.remove();if(!$('qqBatteryCapacityRow')){const d=document.createElement('div');d.id='qqBatteryCapacityRow';d.style.display='none';d.innerHTML='<span>Capacidad banco de baterías</span><strong id="qqBatteryCapacity">—</strong>';grid.appendChild(d)}if(!$('qqBackupConsumptionRow')){const d=document.createElement('div');d.id='qqBackupConsumptionRow';d.style.display='none';d.innerHTML='<span>Consumo a respaldar</span><strong id="qqBackupConsumption">—</strong>';grid.appendChild(d)}}
function syncExtras(){ensureFields();const eq=selectedEquipment(),vfd=eq.type==='vfd';const qLabel=$('qqInvQty')?.previousElementSibling,qPower=$('qqInvPower');if(qLabel)qLabel.textContent=vfd?'VARIADOR SOLAR(ES)':'INVERSOR(ES)';if(qPower)qPower.textContent=vfd?vfdPower():qPower.textContent;const icon=qLabel?.parentElement?.querySelector('.qstat-icon img')||qPower?.parentElement?.querySelector('.qstat-icon img');if(icon){icon.src=vfd?'quote-vfd-icon.svg':'quote-inverter-icon.png';icon.alt=vfd?'Variador de frecuencia solar':'Inversor fotovoltaico'}const techInvLabel=$('qqTechInv')?.parentElement?.querySelector('span');if(techInvLabel)techInvLabel.textContent=vfd?'Variador(es) solar':'Inversor(es)';if(vfd&&$('qqTechInv'))$('qqTechInv').textContent=vfdPower();if(vfd&&$('qqTechAc'))$('qqTechAc').textContent='No aplica — variador solar';
 const offgrid=($('systemType')?.value||'ON-GRID')==='OFF-GRID',batteryRow=$('qqBatteryCapacityRow'),backupRow=$('qqBackupConsumptionRow');
 const oldType=$('qqBatteryTypeRow'),oldQty=$('qqBatteryQtyRow');if(oldType)oldType.style.display='none';if(oldQty)oldQty.style.display='none';
 if(batteryRow){const o=$('battery')?.selectedOptions?.[0],tech=$('batteryTechNote')?.textContent||'',src=tech||o?.textContent||'',cm=src.match(/([\d.,]+)\s*kWh\s*nominal/i)||src.match(/([\d.,]+)\s*kWh/i),unit=cm?parseFloat(cm[1].replace(/\./g,'').replace(',','.')):0,qt=$('qqTechBatteryQty')?.textContent||'',qm=qt.match(/([\d.,]+)/),qty=qm?parseFloat(qm[1].replace(/\./g,'').replace(',','.')):1;if(offgrid&&unit>0){batteryRow.style.display='block';const total=unit*qty;$('qqBatteryCapacity').textContent=qty>1?`${fmt(total,2)} kWh nominales (${fmt(qty,0)} × ${fmt(unit,2)} kWh)`:`${fmt(unit,2)} kWh nominales`}else batteryRow.style.display='none'}
 if(backupRow){const b=matrixBackup();if(offgrid&&(b.daily>0||b.monthly>0||b.annual>0)){backupRow.style.display='block';$('qqBackupConsumption').textContent=`${fmt(b.daily,2)} kWh/día · ${fmt(b.monthly,2)} kWh/mes · ${fmt(b.annual,2)} kWh/año`}else backupRow.style.display='none'}
}
function install(){ensureFields();if(typeof window.syncQuoteDocument==='function'&&!window.syncQuoteDocument.__quotePatch){const orig=window.syncQuoteDocument,wrapped=function(){orig();syncExtras()};wrapped.__quotePatch=true;window.syncQuoteDocument=wrapped}syncExtras();setTimeout(syncExtras,300);setTimeout(syncExtras,1000);['systemType','systemPhase','equipmentMode','solarVfd','inverter','battery','batteryMode','batteryStorageHours'].forEach(id=>$(id)?.addEventListener('change',()=>setTimeout(syncExtras,0)));document.addEventListener('input',e=>{if(e.target.closest('#consumptionMatrixBody'))setTimeout(syncExtras,0)})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
})();
