(() => {
  'use strict';
  const app=document.getElementById('app');
  const state={client:{name:'',city:'',phone:''},view:'portal'};
  const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
  const render=()=>{
    if(state.view==='portal') return portal();
    if(state.view==='home') return home();
    if(state.view==='calculo') return calculo();
    if(state.view==='nuevo') return nuevo();
    if(state.view==='saved') return saved();
    if(state.view==='proyectos') return simplePage('PROYECTOS AGPE','Gestión y seguimiento de proyectos AGPE.','Módulo base preparado para incorporar estados, documentación, hitos, responsables y trazabilidad.');
    if(state.view==='clientes') return simplePage('CLIENTES','Administración de clientes.','Módulo base preparado para la ficha del cliente, contacto, proyectos asociados y documentación.');
  };
  function portal(){app.innerHTML=`<div class="app portal"><div class="portal-card"><div class="brand"><div class="brand-mark">e</div><div class="brand-name"><span>e-</span>SUN POWER</div><div class="tag">SOLAR ENERGY SOLUTIONS</div></div><h1>PORTAL DE ACCESO</h1><div class="muted">E-SUN POWER AGPE · Plataforma de diseño fotovoltaico</div><div class="field"><label>Nombre / razón social</label><input id="clientName" placeholder="Ingrese nombre o razón social"></div><div class="field"><label>Ciudad de ubicación del proyecto</label><input id="clientCity" placeholder="Ingrese ciudad"></div><div class="field"><label>Teléfono</label><input id="clientPhone" placeholder="Ingrese teléfono"></div><button class="primary" id="enter">INGRESAR A E-SUN POWER AGPE</button><div class="status">Aplicación independiente · Arquitectura AGPE v1.0</div></div></div>`;document.getElementById('enter').onclick=()=>{state.client={name:document.getElementById('clientName').value,city:document.getElementById('clientCity').value,phone:document.getElementById('clientPhone').value};state.view='home';render()}};
  function topbar(){return `<header class="topbar"><div class="top-brand"><div class="mini-mark">e</div><div><strong>E-SUN POWER AGPE</strong><small>SOLAR ENERGY SOLUTIONS</small></div></div><button class="logout" id="logout">SALIR</button></header>`}
  function home(){app.innerHTML=`<div class="app shell">${topbar()}<main class="workspace"><div class="welcome"><div class="eyebrow">PLATAFORMA AGPE</div><h1>E-SUN POWER AGPE</h1><p>Diseño, dimensionamiento y gestión de proyectos de autogeneración a pequeña escala.</p></div><div class="grid"><button class="card featured" data-v="calculo"><div class="card-icon">01</div><h2>CÁLCULO DE</h2><p>Crear, dimensionar y evaluar proyectos fotovoltaicos.</p></button><button class="card" data-v="proyectos"><div class="card-icon">02</div><h2>PROYECTOS AGPE</h2><p>Gestión y seguimiento de proyectos AGPE.</p></button><button class="card" data-v="clientes"><div class="card-icon">03</div><h2>CLIENTES</h2><p>Administración de clientes y proyectos asociados.</p></button></div><div class="status">${state.client.name?`Cliente de sesión: <strong>${esc(state.client.name)}</strong>${state.client.city?' · '+esc(state.client.city):''}`:'Sesión sin datos de cliente.'}</div></main></div>`;wire();}
  function calculo(){app.innerHTML=`<div class="app shell">${topbar()}<main class="workspace subpage"><button class="back" data-v="home">← VOLVER</button><div class="crumb">E-SUN POWER AGPE / CÁLCULO DE</div><h1>CÁLCULO DE</h1><p>Seleccione una operación.</p><div class="choice-grid"><button class="card featured choice" data-v="nuevo"><div class="card-icon">01</div><h2>NUEVO PROYECTO</h2><p>Iniciar un proyecto y seleccionar la tecnología fotovoltaica.</p></button><button class="card choice" data-v="saved"><div class="card-icon">02</div><h2>PROYECTOS GUARDADOS</h2><p>Consultar y abrir proyectos previamente almacenados.</p></button></div></main></div>`;wire()}
  function nuevo(){app.innerHTML=`<div class="app shell">${topbar()}<main class="workspace subpage"><button class="back" data-v="calculo">← VOLVER</button><div class="crumb">E-SUN POWER AGPE / CÁLCULO DE / NUEVO PROYECTO</div><h1>NUEVO PROYECTO</h1><p>Seleccione el tipo de sistema que desea diseñar.</p><div class="choice-grid"><button class="card featured choice" data-type="traditional"><div class="card-icon">SFV</div><h2>SFV TRADICIONAL</h2><p>Sistema fotovoltaico para autogeneración con selección de módulos, inversor, estructura, baterías y demás componentes.</p></button><button class="card featured choice" data-type="pumping"><div class="card-icon">PV</div><h2>SFV BOMBEO SOLAR</h2><p>Sistema fotovoltaico para bombeo con motor, variador de frecuencia solar y dimensionamiento energético.</p></button></div><div class="status">Los motores de cálculo se incorporarán como módulos independientes. Esta pantalla no depende del aplicativo V153.26.</div></main></div>`;wire()}
  function saved(){let projects=JSON.parse(localStorage.getItem('esun_agpe_projects')||'[]');app.innerHTML=`<div class="app shell">${topbar()}<main class="workspace subpage"><button class="back" data-v="calculo">← VOLVER</button><div class="crumb">E-SUN POWER AGPE / CÁLCULO DE / PROYECTOS GUARDADOS</div><h1>PROYECTOS GUARDADOS</h1><p>Proyectos almacenados en este navegador.</p><div class="saved">${projects.length?projects.map((p,i)=>`<div class="status"><strong>${esc(p.name||'Proyecto sin nombre')}</strong> · ${esc(p.type||'AGPE')}<br><small>${esc(p.date||'')}</small></div>`).join(''):`<div class="empty"><strong>AÚN NO HAY PROYECTOS</strong>Los proyectos aparecerán aquí cuando construyamos el módulo de creación y guardado.</div>`}</div></main></div>`;wire()}
  function simplePage(title,sub,body){app.innerHTML=`<div class="app shell">${topbar()}<main class="workspace subpage"><button class="back" data-v="home">← VOLVER</button><div class="crumb">E-SUN POWER AGPE / ${esc(title)}</div><h1>${esc(title)}</h1><p>${esc(sub)}</p><div class="placeholder"><strong>${esc(title)}</strong><p>${esc(body)}</p><div class="status">Módulo estructural inicial. Se desarrollará posteriormente dentro de E-SUN POWER AGPE.</div></div></main></div>`;wire()}
  function wire(){document.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{state.view=b.dataset.v;render()});document.getElementById('logout')?.addEventListener('click',()=>{state.view='portal';render()});document.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>{localStorage.setItem('esun_agpe_pending_type',b.dataset.type);const projects=JSON.parse(localStorage.getItem('esun_agpe_projects')||'[]');projects.push({name:'Nuevo proyecto',type:b.dataset.type==='pumping'?'SFV BOMBEO SOLAR':'SFV TRADICIONAL',date:new Date().toLocaleString('es-CO')});localStorage.setItem('esun_agpe_projects',JSON.stringify(projects));state.view='calculo';render()})}
  render();
})();
